use python3, use CORS
nutratech/nutra-server pull request #58
Opened 2022-06-29 22:47 UTC by KthProg

2022-06-29 22:48 UTC, gamesguru commented
Don't use python3 in the makefile

Instead copy it on your machine so both point to python3

2022-06-29 22:51 UTC, KthProg commented
> Don't use python3 in the makefile
> 
> Instead copy it on your machine so both point to python3
> 
> venv should be easy to set up too and that will populate your PATH with an isolate python environment

Fixed it

2022-06-29 22:59 UTC, gamesguru commented
You need to deploy dev to merge to master or prod.

git push origin HEAD:dev

2022-06-29 23:01 UTC, gamesguru requested changes

2022-06-29 23:01 UTC, gamesguru commented on ntserv/routes.py
> +app.config.CORS_ORIGINS = "http://localhost:3000,https://nutra.tk"
dev.nutra.tk

These should be imported from the init

2022-06-29 23:17 UTC, gamesguru commented
this is causing massive duplication on the auto-generated url map

these would have to be filtered out

is there a reason we need to support CORS today? Does fetch work without it

2022-06-30 01:07 UTC, gamesguru commented on ntserv/routes.py
> +    return exc_req(get_nutrients, request)
is this needed?

2022-07-02 05:10 UTC, merged